// Generated by CoffeeScript 1.6.3
var print, socket;

socket = io.connect('http://localhost');

print = function(msg) {
  return $('#log').append($('<p>').text(msg));
};

socket.on('chat', function(data) {
  return print(data.msg);
});

$('#btn_send').click(function() {
  var msg;
  msg = $('#msg_body').val();
  return socket.emit('chat', {
    msg: msg
  });
});
