// Generated by CoffeeScript 1.6.3
var print, socket;

print = function(msg) {
  return $('#log').append($('<p>').text(msg));
};

socket = io.connect('http://localhost');

socket.on('connect', function() {
  var room, shebang;
  room = (shebang = location.href.match(/#([^#]+)$/)) ? shebang[1] : 'default';
  socket.emit('join_to_room', room);
  return print("connect!!! (room:" + room + ")");
});

socket.on('chat', function(data) {
  return print(data.msg);
});

$('#btn_send').click(function() {
  var msg;
  msg = $('#msg_body').val();
  return socket.emit('chat', {
    msg: msg
  });
});
