// Generated by CoffeeScript 1.6.3
var print, send_msg, socket;

print = function(msg) {
  return $('#log').prepend($('<p>').text(msg));
};

socket = io.connect("" + location.protocol + "//" + location.hostname);

socket.on('connect', function() {
  var room, shebang;
  room = (shebang = location.href.match(/#([^#]+)$/)) ? shebang[1] : 'room1';
  socket.emit('join_to_room', room);
  return print("connect!!! (room:" + room + ")");
});

socket.on('chat', function(data) {
  return print(data.msg);
});

send_msg = function() {
  var msg;
  msg = $('#msg_body').val();
  socket.emit('chat', {
    msg: msg
  });
  return $('#msg_body').val('');
};

$('#btn_send').click(send_msg);

$('#msg_body').on('keydown', function(e) {
  if (e.keyCode === 13) {
    return send_msg();
  }
});

socket.on('rooms', function(rooms) {
  var dom, name, num, _results;
  dom = $('#rooms').html('');
  _results = [];
  for (name in rooms) {
    num = rooms[name];
    dom.append($('<a>').attr('href', location.origin + '#' + name).attr('target', '_blank').text("#" + name + "(" + num + ")"));
    _results.push(dom.append(' '));
  }
  return _results;
});
